#!/bin/bash

cp "Data_Files/configuration.txt" "build/configuration.txt"
cp "Data_Files/ReadMe.txt" "build/ReadMe.txt"
cp "Data_Files/merge_nations.txt" "build/merge_nations.txt" 
cp "Data_Files/starting_factories.txt" "build/starting_factories.txt" 
cp "Data_Files/province_mappings.txt" "build/province_mappings.txt"
cp "Data_Files/country_mappings.txt" "build/country_mappings.txt"
cp "Data_Files/cultureMap.txt" "build/cultureMap.txt"
cp "Data_Files/slaveCultureMap.txt" "build/slaveCultureMap.txt"
cp "Data_Files/religionMap.txt" "build/religionMap.txt"
cp "Data_Files/unions.txt" "build/unions.txt"
cp "Data_Files/governmentMapping.txt" "build/governmentMapping.txt"
cp "Data_Files/blocked_tech_schools.txt" "build/blocked_tech_schools.txt"
cp "Data_Files/leader_traits.txt" "build/leader_traits.txt"
cp "Data_Files/regiment_costs.txt" "build/regiment_costs.txt"
cp "Data_Files/license.txt" "build/license.txt"
cp "Data_Files/idea_effects.txt" "build/idea_effects.txt"
cp "Data_Files/Colonial.txt" "build/Colonial.txt"
cp "Data_Files/ck2titleMap.txt" "build/ck2titleMap.txt"
cp "Data_Files/port_blacklist.txt" "build/port_blacklist.txt"
cp "Data_Files/port_whitelist.txt" "build/port_whitelist.txt"
cp "Data_Files/minorityPops.txt" "build/minorityPops.txt"
cp "Data_Files/FAQ.txt" "build/FAQ.txt" 

rm -r "build/blankMod"
mkdir "build/blankMod"
mkdir "build/blankMod/output"
mkdir "build/blankMod/output/decisions"
mkdir "build/blankMod/output/events"
mkdir "build/blankMod/output/history"
mkdir "build/blankMod/output/history/provinces"
mkdir "build/blankMod/output/history/provinces/africa"
mkdir "build/blankMod/output/history/provinces/asia"
mkdir "build/blankMod/output/history/provinces/australia"
mkdir "build/blankMod/output/history/provinces/austria"
mkdir "build/blankMod/output/history/provinces/balkan"
mkdir "build/blankMod/output/history/provinces/canada"
mkdir "build/blankMod/output/history/provinces/carribean"
mkdir "build/blankMod/output/history/provinces/central asia"
mkdir "build/blankMod/output/history/provinces/china"
mkdir "build/blankMod/output/history/provinces/france"
mkdir "build/blankMod/output/history/provinces/germany"
mkdir "build/blankMod/output/history/provinces/india"
mkdir "build/blankMod/output/history/provinces/indonesia"
mkdir "build/blankMod/output/history/provinces/italy"
mkdir "build/blankMod/output/history/provinces/japan"
mkdir "build/blankMod/output/history/provinces/low countries"
mkdir "build/blankMod/output/history/provinces/mexico"
mkdir "build/blankMod/output/history/provinces/pacific island"
mkdir "build/blankMod/output/history/provinces/portugal"
mkdir "build/blankMod/output/history/provinces/scandinavia"
mkdir "build/blankMod/output/history/provinces/south america"
mkdir "build/blankMod/output/history/provinces/soviet"
mkdir "build/blankMod/output/history/provinces/spain"
mkdir "build/blankMod/output/history/provinces/united kingdom"
mkdir "build/blankMod/output/history/provinces/usa"
mkdir "build/blankMod/output/history/countries"
mkdir "build/blankMod/output/history/diplomacy"
mkdir "build/blankMod/output/history/units"
mkdir "build/blankMod/output/history/pops"
mkdir "build/blankMod/output/history/pops/1836.1.1"
mkdir "build/blankMod/output/history/wars"
mkdir "build/blankMod/output/common"
mkdir "build/blankMod/output/common/countries"

cp -r "Data_Files/countries" "build/blankMod/output/common/"
cp -r "Data_Files/gfx" "build/blankMod/output/"
cp -r "Data_Files/localisation" "build/blankMod/output/"
cp -r "Data_Files/interface" "build/blankMod/output/"
cp -r "Data_Files/wars" "build/blankMod/output/history/" 
cp -r "Data_Files/pops" "build/blankMod/output/history/pops/1836.1.1"
cp "Data_Files/converterEvents.txt" "build/blankMod/output/events/converterEvents.txt"
cp "Data_Files/converterDecisions.txt" "build/blankMod/output/decisions/converterDecisions.txt"
cp "Data_Files/countries.txt" "build/blankMod/output/common/countries.txt"
cp "Data_Files/country_colors.txt" "build/blankMod/output/common/country_colors.txt"
cp "Data_Files/religion.txt" "build/blankMod/output/common/religion.txt"
cp "Data_Files/cultures.txt" "build/blankMod/output/common/cultures.txt"
